// examples/basic-crud-application/vue-client/src/App.vue
<script setup>
import { computed, ref } from "vue";
import { useTodoStore } from "@/stores/todo";
import { socket } from "@/socket";

const newTodo = ref("");
const editedTodo = ref(undefined);
const newTitle = ref("");

const store = useTodoStore();

// remove any existing listeners (in case of hot reload)
socket.off();

store.bindEvents();

function addTodo() {
  const value = newTodo.value && newTodo.value.trim();
  if (!value) {
    return;
  }
  store.add(value);
  newTodo.value = "";
}

function editTodo(todo) {
  editedTodo.value = todo;
  newTitle.value = todo.title;
}

function doneEdit(todo) {
  if (newTitle.value) {
    store.setTitle(todo, newTitle.value);
  } else {
    store.delete(todo);
  }
  editedTodo.value = undefined;
}

function cancelEdit() {
  editedTodo.value = undefined;
}

const allDone = computed({
  get: () => {
    return store.remaining === 0;
  },
  set: (value) => {
    store.toggleAll(value);
  },
});

function pluralize(word, count) {
  return word + (count === 1 ? "" : "s");
}
</script>

<template>
  <section class="todoapp" v-cloak>
    <header class="header">
      <h1>todos</h1>
      <input
        class="new-todo"
        autofocus
        autocomplete="off"
        placeholder="What needs to be done?"
        v-model="newTodo"
        @keydown.enter="addTodo"
      />
    </header>
    <section class="main" v-show="store.todos.length">
      <input
        id="toggle-all"
        class="toggle-all"
        type="checkbox"
        v-model="allDone"
      />
      <label for="toggle-all">Mark all as complete</label>
      <ul class="todo-list">
        <li
          class="todo"
          v-for="todo in store.todos"
          :key="todo.id"
          :class="{ completed: todo.completed, editing: todo === editedTodo }"
        >
          <div class="view">
            <input
              class="toggle"
              type="checkbox"
              v-model="todo.completed"
              @click="store.toggleOne(todo)"
            />
            <label @dblclick="editTodo(todo)">{{ todo.title }}</label>
            <button class="destroy" @click="store.delete(todo)"></button>
          </div>
          <input
            class="edit"
            type="text"
            v-model="newTitle"
            @blur="doneEdit"
            @keydown.enter="doneEdit(todo)"
            @keydown.esc="cancelEdit(todo)"
          />
        </li>
      </ul>
    </section>
    <footer class="footer" v-show="store.todos.length">
      <span class="todo-count">
        <strong v-text="store.remaining"></strong>
        {{ pluralize("item", store.remaining) }} left
      </span>
      <button
        class="clear-completed"
        @click="store.deleteCompleted"
        v-show="store.todos.length > store.remaining"
      >
        Clear complete
      </button>
    </footer>
  </section>
</template>

<style scoped></style>

// examples/basic-crud-application/angular-client/src/app/app.component.ts
import { Component } from '@angular/core';
import { TodoStore, Todo } from './store';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  todoStore: TodoStore;
  newTodoText = '';

  constructor(todoStore: TodoStore) {
    this.todoStore = todoStore;
  }

  stopEditing(todo: Todo, editedTitle: string) {
    todo.title = editedTitle;
    todo.editing = false;
  }

  cancelEditingTodo(todo: Todo) {
    todo.editing = false;
  }

  updateEditingTodo(todo: Todo, editedTitle: string) {
    editedTitle = editedTitle.trim();
    todo.editing = false;

    if (editedTitle.length === 0) {
      return this.todoStore.remove(todo);
    }

    todo.title = editedTitle;
  }

  editTodo(todo: Todo) {
    todo.editing = true;
  }

  removeCompleted() {
    this.todoStore.removeCompleted();
  }

  toggleCompletion(todo: Todo) {
    this.todoStore.toggleCompletion(todo);
  }

  remove(todo: Todo){
    this.todoStore.remove(todo);
  }

  addTodo() {
    if (this.newTodoText.trim().length) {
      this.todoStore.add(this.newTodoText);
      this.newTodoText = '';
    }
  }
}

<section class="todoapp">
  <header class="header">
    <h1>todos</h1>
    <input class="new-todo" placeholder="What needs to be done?" autofocus="" [(ngModel)]="newTodoText" (keyup.enter)="addTodo()">
  </header>
  <section class="main" *ngIf="todoStore.todos.length > 0">
    <input id="toggle-all" class="toggle-all" type="checkbox" *ngIf="todoStore.todos.length" #toggleall [checked]="todoStore.allCompleted()" (click)="todoStore.setAllTo(toggleall.checked)">
    <ul class="todo-list">
      <li *ngFor="let todo of todoStore.todos" [class.completed]="todo.completed" [class.editing]="todo.editing">
        <div class="view">
          <input class="toggle" type="checkbox" (click)="toggleCompletion(todo)" [checked]="todo.completed">
          <label (dblclick)="editTodo(todo)">{{todo.title}}</label>
          <button class="destroy" (click)="remove(todo)"></button>
        </div>
        <input class="edit" *ngIf="todo.editing" [value]="todo.title" #editedtodo (blur)="stopEditing(todo, editedtodo.value)" (keyup.enter)="updateEditingTodo(todo, editedtodo.value)" (keyup.escape)="cancelEditingTodo(todo)">
      </li>
    </ul>
  </section>
  <footer class="footer" *ngIf="todoStore.todos.length > 0">
    <span class="todo-count"><strong>{{todoStore.getRemaining().length}}</strong> {{todoStore.getRemaining().length == 1 ? 'item' : 'items'}} left</span>
    <button class="clear-completed" *ngIf="todoStore.getCompleted().length > 0" (click)="removeCompleted()">Clear completed</button>
  </footer>
</section>
